- name: Hello World Sample
  hosts: localhost
  tasks:    
    - name: Get facts
      azure_rm_resourcegroup_facts:
      register: output
      
    - debug: var=output
    
    - name: Power On
      azure_rm_virtualmachine:
        resource_group: EXTEDO-China-Demo
        name: "{{ vm-name }}"    
      
