- name: Hello World Sample
  hosts: localhost
  gather_facts: True
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"      
    - name: Get facts
      azure_rm_resourcegroup_facts:
      debug:
        var: result
